### ISSUE TITLE
wildcard error in line 242 SnakeMake File

### ISSUE THREAD

**Issue by saras224** [bhattlab/lathe#21] opened 2021-08-10 10:07 UTC
Hi @elimoss @bsiranosian 

I have used this command:

snakemake --use-singularity --singularity-args '--bind /home/rsharma/ ' -s /home/rsharma/lathe/Snakefile --configfile /home/rsharma/lathe/config.yaml --restart-times 0 --keep-going --latency-wait 30 --cores 10

After this it says building DAG of jobs and gives this error:

Building DAG of jobs...
WildcardError in line 242 of /home/rsharma/lathe/Snakefile:
Wildcards in input files cannot be determined from output files:
'contig_cutoff'

My config.txt
[config.txt](https://github.com/bhattlab/lathe/files/6960740/config.txt)
 file

file_names.txt:
[file_names.txt](https://github.com/bhattlab/lathe/files/6960742/file_names.txt)

I have posted my issue and waiting since last two weeks. Please tell me how do I resolve the error so that I can use your tool for proceeding with the analysis.

Thanks in Advance 
Saraswati Awasthi

**Comment by dgmaghini** [comment] 2021-08-10 23:03
Duplicate of #20 .

**Closed by dgmaghini** 2021-08-10 23:03 UTC
